---
# An employee record
name: Default Programmer
job: Developer
skill: Elite
employed: True
# A list of tasty fruits
foods:
    - Apple
    - Orange
    - Strawberry
    - Mango
# Mine languages
languages:
    perl: Elite
    python: Elite
    pascal: Lame
education: |
    4 GCSEs
    3 A-Levels
    BSc in the Internet of Things
# Employee records
employees:
 -  martin:
    name: Martin D'vloper
    job: Developer
    skills:
      - python
      - perl
      - pascal
 -  tabitha:
    name: Tabitha Bitumen
    job: Developer
    skills:
      - lisp
      - fortran
      - erlang